package raylras.zen.code.tree;

import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.TerminalNode;
import raylras.zen.code.Range;
import raylras.zen.code.parser.ZenScriptLexer;
import raylras.zen.code.parser.ZenScriptParser;
import raylras.zen.code.parser.ZenScriptParserBaseVisitor;
import raylras.zen.code.tree.expr.*;
import raylras.zen.code.tree.stmt.*;
import raylras.zen.code.type.*;

import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Class used to build an Abstract Syntax Tree (AST)
 * from a Concrete Syntax Tree (CST) generated by ANTLR4.
 */
public class TreeBuilder extends ZenScriptParserBaseVisitor<Object> {

    /* Internals */

    private static final int ANTLR4_START_LINE = 1;
    private static final int ANTLR4_START_COLUM = 0;
    private static final int LINE_OFFSET = Range.FIRST_LINE - ANTLR4_START_LINE;
    private static final int COLUMN_OFFSET = Range.FIRST_COLUMN - ANTLR4_START_COLUM;

    private static Range getRange(ParserRuleContext cst) {
        if (cst == null) return null;
        return new Range(cst.start.getLine() + LINE_OFFSET,
                cst.start.getCharPositionInLine() + COLUMN_OFFSET,
                cst.stop.getLine() + LINE_OFFSET,
                cst.stop.getCharPositionInLine() + cst.stop.getText().length() + COLUMN_OFFSET);
    }

    private static Range getRange(TerminalNode cst) {
        if (cst == null) return null;
        return new Range(cst.getSymbol().getLine() + LINE_OFFSET,
                cst.getSymbol().getCharPositionInLine() + COLUMN_OFFSET,
                cst.getSymbol().getLine() + LINE_OFFSET,
                cst.getSymbol().getCharPositionInLine() + cst.getText().length() + COLUMN_OFFSET);
    }

    private SimpleName getSimpleName(TerminalNode node) {
        if (node == null) return null;
        return new SimpleName(node.getText(), getRange(node));
    }

    private Unary.Operator getUnaryOp(Token token) {
        if (token == null) return null;
        switch (token.getType()) {
            case ZenScriptLexer.NOT:
                return Unary.Operator.NOT;

            case ZenScriptLexer.ADD:
                return Unary.Operator.POS;

            case ZenScriptLexer.SUB:
                return Unary.Operator.NEG;

            default:
                return Unary.Operator.INVALID;
        }
    }

    private Binary.Operator getBinaryOp(Token token) {
        if (token == null) return null;
        switch (token.getType()) {
            case ZenScriptLexer.ADD:
                return Binary.Operator.ADD;

            case ZenScriptLexer.SUB:
                return Binary.Operator.SUB;

            case ZenScriptLexer.MUL:
                return Binary.Operator.MUL;

            case ZenScriptLexer.DIV:
                return Binary.Operator.DIV;

            case ZenScriptLexer.MOD:
                return Binary.Operator.MOD;

            case ZenScriptLexer.CAT:
                return Binary.Operator.CAT;

            case ZenScriptLexer.LESS:
                return Binary.Operator.LESS;

            case ZenScriptLexer.GREATER:
                return Binary.Operator.GREATER;

            case ZenScriptLexer.LESS_EQUAL:
                return Binary.Operator.LESS_EQUALS;

            case ZenScriptLexer.GREATER_EQUAL:
                return Binary.Operator.GREATER_EQUALS;

            case ZenScriptLexer.AND:
                return Binary.Operator.BITWISE_AND;

            case ZenScriptLexer.OR:
                return Binary.Operator.BITWISE_OR;

            case ZenScriptLexer.AND_AND:
                return Binary.Operator.LOGICAL_AND;

            case ZenScriptLexer.OR_OR:
                return Binary.Operator.LOGICAL_OR;

            case ZenScriptLexer.EQUAL:
                return Binary.Operator.EQUALS;

            case ZenScriptLexer.NOT_EQUAL:
                return Binary.Operator.NOT_EQUALS;

            default:
                return Binary.Operator.INVALID;
        }
    }

    private Assignment.Operator getAssignOp(Token token) {
        if (token == null) return null;
        switch (token.getType()) {
            case ZenScriptLexer.ASSIGN:
                return Assignment.Operator.ASSIGN;

            case ZenScriptLexer.ADD_ASSIGN:
                return Assignment.Operator.ADD_ASSIGN;

            case ZenScriptLexer.SUB_ASSIGN:
                return Assignment.Operator.SUB_ASSIGN;

            case ZenScriptLexer.MUL_ASSIGN:
                return Assignment.Operator.MUL_ASSIGN;

            case ZenScriptLexer.DIV_ASSIGN:
                return Assignment.Operator.DIV_ASSIGN;

            case ZenScriptLexer.MOD_ASSIGN:
                return Assignment.Operator.MOD_ASSIGN;

            case ZenScriptLexer.XOR_ASSIGN:
                return Assignment.Operator.XOR_ASSIGN;

            case ZenScriptLexer.AND_ASSIGN:
                return Assignment.Operator.AND_ASSIGN;

            case ZenScriptLexer.OR_ASSIGN:
                return Assignment.Operator.OR_ASSIGN;

            case ZenScriptLexer.CAT_ASSIGN:
                return Assignment.Operator.CAT_ASSIGN;

            default:
                return Assignment.Operator.INVALID;
        }
    }

    private Declarator getDeclarator(Token token) {
        if (token == null) return null;
        switch (token.getType()) {
            case ZenScriptLexer.VAR:
                return Declarator.VAR;

            case ZenScriptLexer.VAL:
                return Declarator.VAL;

            case ZenScriptLexer.STATIC:
                return Declarator.STATIC;

            case ZenScriptLexer.GLOBAL:
                return Declarator.GLOBAL;

            default:
                return Declarator.NONE;
        }
    }

    private Type getType(ZenScriptParser.TypeLiteralContext ctx) {
        if (ctx == null) return null;
        TypeLiteral literal = visitTypeLiteral(ctx);
        if (literal == null) return null;
        return literal.type;
    }

    private List<Type> getTypeList(ZenScriptParser.TypeLiteralListContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return visitTypeLiteralList(ctx).stream().map(literal -> literal.type).filter(Objects::nonNull).collect(Collectors.toList());
    }

    /* End Internals */

    @Override
    public CompilationUnit visitCompilationUnit(ZenScriptParser.CompilationUnitContext ctx) {
        if (ctx == null) return null;
        List<ImportDeclaration> imports = ctx.importDeclaration().stream().map(this::visitImportDeclaration).filter(Objects::nonNull).collect(Collectors.toList());
        List<ClassDeclaration> classes = ctx.classDeclaration().stream().map(this::visitClassDeclaration).filter(Objects::nonNull).collect(Collectors.toList());
        List<FunctionDeclaration> functions = ctx.functionDeclaration().stream().map(this::visitFunctionDeclaration).filter(Objects::nonNull).collect(Collectors.toList());
        List<Statement> statements = ctx.statement().stream().map(this::visitStatement).filter(Objects::nonNull).collect(Collectors.toList());
        Range range = getRange(ctx);
        return new CompilationUnit(imports, classes, functions, statements, range);
    }

    @Override
    public ImportDeclaration visitImportDeclaration(ZenScriptParser.ImportDeclarationContext ctx) {
        if (ctx == null) return null;
        Name name = visitQualifiedName(ctx.qualifiedName());
        SimpleName alias = visitAlias(ctx.alias());
        Range range = getRange(ctx);
        return new ImportDeclaration(name, alias, range);
    }

    @Override
    public Name visitQualifiedName(ZenScriptParser.QualifiedNameContext ctx) {
        if (ctx == null) return null;
        List<SimpleName> nameList = ctx.IDENTIFIER().stream().map(this::getSimpleName).filter(Objects::nonNull).collect(Collectors.toList());
        Name name = nameList.get(0);
        for (int i = 1; i < nameList.size(); i++) {
            SimpleName next = nameList.get(i);
            name = new QualifiedName(name, next, new Range(name.range.startLine, name.range.startColumn, next.range.endLine, next.range.endColumn));
        }
        return name;
    }

    @Override
    public SimpleName visitAlias(ZenScriptParser.AliasContext ctx) {
        if (ctx == null) return null;
        return getSimpleName(ctx.IDENTIFIER());
    }

    @Override
    public FunctionDeclaration visitFunctionDeclaration(ZenScriptParser.FunctionDeclarationContext ctx) {
        if (ctx == null) return null;
        SimpleName name = getSimpleName(ctx.IDENTIFIER());
        List<ParameterDeclaration> params = visitParameterList(ctx.parameterList());
        TypeLiteral returnType = visitTypeLiteral(ctx.typeLiteral());
        List<Statement> statements = visitFunctionBody(ctx.functionBody());
        Range range = getRange(ctx);
        return new FunctionDeclaration(name, params, returnType, statements, range);
    }

    @Override
    public List<ParameterDeclaration> visitParameterList(ZenScriptParser.ParameterListContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return ctx.parameter().stream().map(this::visitParameter).filter(Objects::nonNull).collect(Collectors.toList());
    }

    @Override
    public ParameterDeclaration visitParameter(ZenScriptParser.ParameterContext ctx) {
        if (ctx == null) return null;
        SimpleName name = getSimpleName(ctx.IDENTIFIER());
        TypeLiteral typeDecl = visitTypeLiteral(ctx.typeLiteral());
        Expression defaultValue = visitDefaultValue(ctx.defaultValue());
        Range range = getRange(ctx);
        return new ParameterDeclaration(name, typeDecl, defaultValue, range);
    }

    @Override
    public Expression visitDefaultValue(ZenScriptParser.DefaultValueContext ctx) {
        if (ctx == null) return null;
        return visitExpression(ctx.expression());
    }

    @Override
    public List<Statement> visitFunctionBody(ZenScriptParser.FunctionBodyContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return ctx.statement().stream().map(this::visitStatement).filter(Objects::nonNull).collect(Collectors.toList());
    }

    @Override
    public ClassDeclaration visitClassDeclaration(ZenScriptParser.ClassDeclarationContext ctx) {
        if (ctx == null) return null;
        SimpleName name = getSimpleName(ctx.IDENTIFIER());
        List<VariableDeclaration> fields = ctx.variableDeclaration().stream().map(this::visitVariableDeclaration).filter(Objects::nonNull).collect(Collectors.toList());
        List<ConstructorDeclaration> constructors = ctx.constructorDeclaration().stream().map(this::visitConstructorDeclaration).filter(Objects::nonNull).collect(Collectors.toList());
        List<FunctionDeclaration> methods = ctx.functionDeclaration().stream().map(this::visitFunctionDeclaration).filter(Objects::nonNull).collect(Collectors.toList());
        Range range = getRange(ctx);
        return new ClassDeclaration(name, fields, constructors, methods, range);
    }

    @Override
    public ConstructorDeclaration visitConstructorDeclaration(ZenScriptParser.ConstructorDeclarationContext ctx) {
        if (ctx == null) return null;
        SimpleName name = getSimpleName(ctx.ZEN_CONSTRUCTOR());
        List<ParameterDeclaration> params = visitParameterList(ctx.parameterList());
        List<Statement> statements = visitConstructorBody(ctx.constructorBody());
        Range range = getRange(ctx);
        return new ConstructorDeclaration(name, params, statements, range);
    }

    @Override
    public List<Statement> visitConstructorBody(ZenScriptParser.ConstructorBodyContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return ctx.statement().stream().map(this::visitStatement).filter(Objects::nonNull).collect(Collectors.toList());
    }

    @Override
    public VariableDeclaration visitVariableDeclaration(ZenScriptParser.VariableDeclarationContext ctx) {
        if (ctx == null) return null;
        Declarator declarator = getDeclarator(ctx.Declarator);
        SimpleName name = getSimpleName(ctx.IDENTIFIER());
        TypeLiteral typeDecl = visitTypeLiteral(ctx.typeLiteral());
        Expression init = visitInitializer(ctx.initializer());
        Range range = getRange(ctx);
        return new VariableDeclaration(declarator, name, typeDecl, init, range);
    }

    @Override
    public Expression visitInitializer(ZenScriptParser.InitializerContext ctx) {
        if (ctx == null) return null;
        return visitExpression(ctx.expression());
    }

    @Override
    public Statement visitStatement(ZenScriptParser.StatementContext ctx) {
        if (ctx == null) return null;
        return (Statement) visitChildren(ctx);
    }

    @Override
    public Block visitBlockStatement(ZenScriptParser.BlockStatementContext ctx) {
        if (ctx == null) return null;
        List<Statement> statements = ctx.statement().stream().map(this::visitStatement).filter(Objects::nonNull).collect(Collectors.toList());
        Range range = getRange(ctx);
        return new Block(statements, range);
    }

    @Override
    public Return visitReturnStatement(ZenScriptParser.ReturnStatementContext ctx) {
        if (ctx == null) return null;
        Expression expr = visitExpression(ctx.expression());
        Range range = getRange(ctx);
        return new Return(expr, range);
    }

    @Override
    public Break visitBreakStatement(ZenScriptParser.BreakStatementContext ctx) {
        if (ctx == null) return null;
        Range range = getRange(ctx);
        return new Break(range);
    }

    @Override
    public Continue visitContinueStatement(ZenScriptParser.ContinueStatementContext ctx) {
        if (ctx == null) return null;
        Range range = getRange(ctx);
        return new Continue(range);
    }

    @Override
    public If visitIfStatement(ZenScriptParser.IfStatementContext ctx) {
        if (ctx == null) return null;
        Expression condition = visitExpression(ctx.expression());
        Statement thenPart = visitThenBody(ctx.thenBody());
        Statement elsePart = visitElseBody(ctx.elseBody());
        Range range = getRange(ctx);
        return new If(condition, thenPart, elsePart, range);
    }

    @Override
    public Statement visitThenBody(ZenScriptParser.ThenBodyContext ctx) {
        if (ctx == null) return null;
        return visitStatement(ctx.statement());
    }

    @Override
    public Statement visitElseBody(ZenScriptParser.ElseBodyContext ctx) {
        if (ctx == null) return null;
        return visitStatement(ctx.statement());
    }

    @Override
    public Foreach visitForeachStatement(ZenScriptParser.ForeachStatementContext ctx) {
        if (ctx == null) return null;
        List<VariableDeclaration> variables = visitSimpleVariableDeclarations(ctx.simpleVariableDeclarations());
        Expression expr = visitExpression(ctx.expression());
        List<Statement> statements = visitForeachBody(ctx.foreachBody());
        Range range = getRange(ctx);
        return new Foreach(variables, expr, statements, range);
    }

    @Override
    public List<VariableDeclaration> visitSimpleVariableDeclarations(ZenScriptParser.SimpleVariableDeclarationsContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return ctx.IDENTIFIER().stream().map(id -> {
            if (id == null) return null;
            Declarator declarator = Declarator.NONE;
            SimpleName name = getSimpleName(id);
            Range range = getRange(id);
            return new VariableDeclaration(declarator, name, null, null, range);
        }).filter(Objects::nonNull).collect(Collectors.toList());
    }

    @Override
    public List<Statement> visitForeachBody(ZenScriptParser.ForeachBodyContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return ctx.statement().stream().map(this::visitStatement).filter(Objects::nonNull).collect(Collectors.toList());
    }

    @Override
    public While visitWhileStatement(ZenScriptParser.WhileStatementContext ctx) {
        if (ctx == null) return null;
        Expression condition = visitExpression(ctx.expression());
        Statement statement = visitStatement(ctx.statement());
        Range range = getRange(ctx);
        return new While(condition, statement, range);
    }

    @Override
    public ExpressionStmt visitExpressionStatement(ZenScriptParser.ExpressionStatementContext ctx) {
        if (ctx == null) return null;
        Expression expr = visitExpression(ctx.expression());
        Range range = getRange(ctx);
        return new ExpressionStmt(expr, range);
    }

    public Expression visitExpression(ZenScriptParser.ExpressionContext ctx) {
        if (ctx == null) return null;
        return (Expression) ctx.accept(this);
    }

    @Override
    public Ternary visitTernary(ZenScriptParser.TernaryContext ctx) {
        if (ctx == null) return null;
        Expression condition = visitExpression(ctx.Condition);
        Expression truePart = visitExpression(ctx.TruePart);
        Expression falsePart = visitExpression(ctx.FalsePart);
        Range range = getRange(ctx);
        return new Ternary(condition, truePart, falsePart, range);
    }

    @Override
    public MemberAccess visitMemberAccess(ZenScriptParser.MemberAccessContext ctx) {
        if (ctx == null) return null;
        Expression left = visitExpression(ctx.Left);
        SimpleName right = getSimpleName(ctx.IDENTIFIER());
        Range range = getRange(ctx);
        return new MemberAccess(left, right, range);
    }

    @Override
    public MapLiteral visitMapInitializer(ZenScriptParser.MapInitializerContext ctx) {
        if (ctx == null) return null;
        List<MapEntry> entries = visitMapEntryList(ctx.mapEntryList());
        Range range = getRange(ctx);
        return new MapLiteral(entries, range);
    }

    @Override
    public MapEntry visitMapEntry(ZenScriptParser.MapEntryContext ctx) {
        if (ctx == null) return null;
        Expression key = visitExpression(ctx.Key);
        Expression value = visitExpression(ctx.Value);
        Range range = getRange(ctx);
        return new MapEntry(key, value, range);
    }

    @Override
    public BracketHandler visitBracketHandler(ZenScriptParser.BracketHandlerContext ctx) {
        if (ctx == null) return null;
        String literal = ctx.getText();
        Range range = getRange(ctx);
        return new BracketHandler(literal, range);
    }

    @Override
    public ArrayLiteral visitArrayInitializer(ZenScriptParser.ArrayInitializerContext ctx) {
        if (ctx == null) return null;
        List<Expression> elements = visitExpressionList(ctx.expressionList());
        Range range = getRange(ctx);
        return new ArrayLiteral(elements, range);
    }

    @Override
    public IntRange visitIntRange(ZenScriptParser.IntRangeContext ctx) {
        if (ctx == null) return null;
        Expression from = visitExpression(ctx.From);
        Expression to = visitExpression(ctx.To);
        Range range = getRange(ctx);
        return new IntRange(from, to, range);
    }

    @Override
    public List<Expression> visitExpressionList(ZenScriptParser.ExpressionListContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return ctx.expression().stream().map(this::visitExpression).filter(Objects::nonNull).collect(Collectors.toList());
    }

    @Override
    public List<MapEntry> visitMapEntryList(ZenScriptParser.MapEntryListContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return ctx.mapEntry().stream().map(this::visitMapEntry).filter(Objects::nonNull).collect(Collectors.toList());
    }

    @Override
    public Call visitCall(ZenScriptParser.CallContext ctx) {
        if (ctx == null) return null;
        Expression left = visitExpression(ctx.Left);
        List<Expression> params = visitExpressionList(ctx.expressionList());
        Range range = getRange(ctx);
        return new Call(left, params, range);
    }

    @Override
    public ArrayAccess visitArrayIndex(ZenScriptParser.ArrayIndexContext ctx) {
        if (ctx == null) return null;
        Expression left = visitExpression(ctx.Left);
        Expression index = visitExpression(ctx.Index);
        Range range = getRange(ctx);
        return new ArrayAccess(left, index, range);
    }

    @Override
    public FunctionExpression visitFunctionExprission(ZenScriptParser.FunctionExprissionContext ctx) {
        if (ctx == null) return null;
        List<ParameterDeclaration> params = visitParameterList(ctx.parameterList());
        TypeLiteral typeDecl = visitTypeLiteral(ctx.typeLiteral());
        List<Statement> statements = visitFunctionBody(ctx.functionBody());
        Range range = getRange(ctx);
        return new FunctionExpression(params, typeDecl, statements, range);
    }

    @Override
    public Binary visitBinary(ZenScriptParser.BinaryContext ctx) {
        if (ctx == null) return null;
        Expression left = visitExpression(ctx.Left);
        Expression right = visitExpression(ctx.Right);
        Binary.Operator op = getBinaryOp(ctx.Op);
        Range range = getRange(ctx);
        return new Binary(left, right, op, range);
    }

    @Override
    public Assignment visitAssignment(ZenScriptParser.AssignmentContext ctx) {
        if (ctx == null) return null;
        Expression left = visitExpression(ctx.Left);
        Expression right = visitExpression(ctx.Right);
        Assignment.Operator op = getAssignOp(ctx.Op);
        Range range = getRange(ctx);
        return new Assignment(left, right, op, range);
    }

    @Override
    public Unary visitUnary(ZenScriptParser.UnaryContext ctx) {
        if (ctx == null) return null;
        Expression expr = visitExpression(ctx.expression());
        Unary.Operator op = getUnaryOp(ctx.Op);
        Range range = getRange(ctx);
        return new Unary(expr, op, range);
    }

    @Override
    public Parens visitParens(ZenScriptParser.ParensContext ctx) {
        if (ctx == null) return null;
        Expression expr = visitExpression(ctx.expression());
        Range range = getRange(ctx);
        return new Parens(expr, range);
    }

    @Override
    public This visitThis(ZenScriptParser.ThisContext ctx) {
        if (ctx == null) return null;
        Range range = getRange(ctx);
        return new This(range);
    }

    @Override
    public Super visitSuper(ZenScriptParser.SuperContext ctx) {
        if (ctx == null) return null;
        Range range = getRange(ctx);
        return new Super(range);
    }

    @Override
    public ConstantExpression visitTrueLiteral(ZenScriptParser.TrueLiteralContext ctx) {
        if (ctx == null) return null;
        Range range = getRange(ctx);
        return new ConstantExpression(Boolean.TRUE, Type.Kind.BOOL, range);
    }

    @Override
    public ConstantExpression visitFalseLiteral(ZenScriptParser.FalseLiteralContext ctx) {
        if (ctx == null) return null;
        Range range = getRange(ctx);
        return new ConstantExpression(Boolean.FALSE, Type.Kind.BOOL, range);
    }

    @Override
    public ConstantExpression visitStringLiteral(ZenScriptParser.StringLiteralContext ctx) {
        if (ctx == null) return null;
        String value = ctx.getText();
        Range range = getRange(ctx);
        return new ConstantExpression(value, Type.Kind.STRING, range);
    }

    @Override
    public ConstantExpression visitNullLiteral(ZenScriptParser.NullLiteralContext ctx) {
        if (ctx == null) return null;
        Range range = getRange(ctx);
        return new ConstantExpression(null, Type.Kind.ANY, range);
    }

    @Override
    public ConstantExpression visitIntLiteral(ZenScriptParser.IntLiteralContext ctx) {
        if (ctx == null) return null;
        Integer value = Integer.decode(ctx.getText());
        Range range = getRange(ctx);
        return new ConstantExpression(value, Type.Kind.INT, range);
    }

    @Override
    public ConstantExpression visitDoubleLiteral(ZenScriptParser.DoubleLiteralContext ctx) {
        if (ctx == null) return null;
        Double value = Double.valueOf(ctx.getText());
        Range range = getRange(ctx);
        return new ConstantExpression(value, Type.Kind.DOUBLE, range);
    }

    @Override
    public ConstantExpression visitFloatLiteral(ZenScriptParser.FloatLiteralContext ctx) {
        if (ctx == null) return null;
        Float value = Float.valueOf(ctx.getText());
        Range range = getRange(ctx);
        return new ConstantExpression(value, Type.Kind.FLOAT, range);
    }

    @Override
    public ConstantExpression visitLongLiteral(ZenScriptParser.LongLiteralContext ctx) {
        if (ctx == null) return null;
        Long value = Long.decode(ctx.getText());
        Range range = getRange(ctx);
        return new ConstantExpression(value, Type.Kind.LONG, range);
    }

    @Override
    public SimpleName visitSimpleNameExpression(ZenScriptParser.SimpleNameExpressionContext ctx) {
        if (ctx == null) return null;
        return getSimpleName(ctx.IDENTIFIER());
    }

    @Override
    public TypeCast visitTypeCast(ZenScriptParser.TypeCastContext ctx) {
        if (ctx == null) return null;
        Expression expr = visitExpression(ctx.expression());
        TypeLiteral type = visitTypeLiteral(ctx.typeLiteral());
        Range range = getRange(ctx);
        return new TypeCast(expr, type, range);
    }

    public TypeLiteral visitTypeLiteral(ZenScriptParser.TypeLiteralContext ctx) {
        if (ctx == null) return null;
        return (TypeLiteral) ctx.accept(this);
    }

    @Override
    public TypeLiteral visitArrayType(ZenScriptParser.ArrayTypeContext ctx) {
        if (ctx == null) return null;
        String literal = ctx.getText();
        Type elementType = getType(ctx.typeLiteral());
        ArrayType type = new ArrayType(elementType);
        Range range = getRange(ctx);
        return new TypeLiteral(literal, type, range);
    }

    @Override
    public TypeLiteral visitFunctionType(ZenScriptParser.FunctionTypeContext ctx) {
        if (ctx == null) return null;
        String literal = ctx.getText();
        List<Type> paramTypes = getTypeList(ctx.typeLiteralList());
        Type returnType = getType(ctx.typeLiteral());
        Type type = new FunctionType(paramTypes, returnType);
        Range range = getRange(ctx);
        return new TypeLiteral(literal, type, range);
    }

    @Override
    public TypeLiteral visitListType(ZenScriptParser.ListTypeContext ctx) {
        if (ctx == null) return null;
        String literal = ctx.getText();
        Type elementType = getType(ctx.typeLiteral());
        Type type = new ListType(elementType);
        Range range = getRange(ctx);
        return new TypeLiteral(literal, type, range);
    }

    @Override
    public TypeLiteral visitPrimitiveType(ZenScriptParser.PrimitiveTypeContext ctx) {
        if (ctx == null) return null;
        String literal = ctx.getText();
        Type.Kind kind;
        switch (ctx.start.getType()) {
            case ZenScriptLexer.ANY:
                kind = Type.Kind.ANY;
                break;

            case ZenScriptLexer.BYTE:
                kind = Type.Kind.BYTE;
                break;

            case ZenScriptLexer.SHORT:
                kind = Type.Kind.SHORT;
                break;

            case ZenScriptLexer.INT:
                kind = Type.Kind.INT;
                break;

            case ZenScriptLexer.LONG:
                kind = Type.Kind.LONG;
                break;

            case ZenScriptLexer.FLOAT:
                kind = Type.Kind.FLOAT;
                break;

            case ZenScriptLexer.DOUBLE:
                kind = Type.Kind.DOUBLE;
                break;

            case ZenScriptLexer.BOOL:
                kind = Type.Kind.BOOL;
                break;

            case ZenScriptLexer.VOID:
                kind = Type.Kind.VOID;
                break;

            case ZenScriptLexer.STRING:
                kind = Type.Kind.STRING;
                break;

            default:
                kind = Type.Kind.NO_KIND;
        }
        Type type = (kind != Type.Kind.NO_KIND) ? new PrimitiveType(kind) : NoType.INSTANCE;
        Range range = getRange(ctx);
        return new TypeLiteral(literal, type, range);
    }

    @Override
    public TypeLiteral visitClassType(ZenScriptParser.ClassTypeContext ctx) {
        if (ctx == null) return null;
        // TODO
        String literal = ctx.getText();
        Range range = getRange(ctx);
        return new TypeLiteral(literal, NoType.INSTANCE, range);
    }

    @Override
    public TypeLiteral visitMapType(ZenScriptParser.MapTypeContext ctx) {
        if (ctx == null) return null;
        String literal = ctx.getText();
        Type keyType = getType(ctx.Key);
        Type valueType = getType(ctx.Value);
        Type type = new MapType(keyType, valueType);
        Range range = getRange(ctx);
        return new TypeLiteral(literal, type, range);
    }

    @Override
    public List<TypeLiteral> visitTypeLiteralList(ZenScriptParser.TypeLiteralListContext ctx) {
        if (ctx == null) return Collections.emptyList();
        return ctx.typeLiteral().stream().map(this::visitTypeLiteral).filter(Objects::nonNull).collect(Collectors.toList());
    }

}
